[package]
name = "moduli-comparison"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
num-bigint = { version = "0.4.6", features = ["rand"] }
rand = "0.8.5"
divan = "0.1.15"

[[bench]]
name = "barrett"
harness = false
path = "src/main.rs"
